name: Test checkout
on:
  workflow_dispatch:
    inputs:
      ignore_cache:
        description: 'Ignore cache and recreate venv'
        required: false
        default: 'false'

jobs:
    build:
      runs-on: ubuntu-latest
    
      steps:
        - name: Checkout code
          uses: actions/checkout@v2
          with:
            ref: "${{ github.ref }}"
            token: ${{ secrets.GITHUB_TOKEN }}

        - name: List files before venv
          run: ls -la
            
        - name: echo workspace
          run: echo $GITHUB_WORKSPACE

        - name: Recreate venv if required
          id: recreate
          if: ${{ github.event.inputs.ignore_cache == 'true' }}
          run: |
            echo "Recreating venv"
            rm -rf ${{ github.workspace }}/.venv

        - name: Find cache
          id: cache
          uses: actions/cache@v4
          with:
            path: ${{ github.workspace }}/.venv
            key: venv-${{ runner.os }}-${{ runner.arch }}-pip-${{ hashFiles('acceptance/requirements.txt') }}
            lookup-only: true

            
        - name: Create venv
          if: steps.cache.outputs.cache-hit != 'true'
          uses: './.github/actions/setup-venv'

        - name: list files after venv
          run: ls -la

        # - name: Clean workspace
        #   shell: bash -leo pipefail {0}
        #   run:
        #     rm -rf ${{ github.workspace }}/*

        # - name: List files after clean
        #   run: ls -la
