name: cleanup caches by a branch
on:
  workflow_dispatch:
    inputs:
      branch:
        description: branch 
        required: false
        default: 'main'

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Cleanup
        run: |
          echo "Fetching list of cache key"
          cacheKeys=$(gh cache list --ref $BRANCH --limit 10 --json id --jq '.[].id')
          echo "Cache_key ids: $cacheKeys"
          

          ## Setting this to not fail the workflow while deleting cache keys.
          set +e
          echo "Deleting caches..."
          for cacheKey in $cacheKeys
          do
              echo "Deleting cache_key id: $cacheKey"
              gh cache delete $cacheKey
          done
          echo "Done"
        env:
          GH_TOKEN: ${{ secrets.WF_PAT }}
          GH_REPO: ${{ github.repository }}
          BRANCH: refs/heads/${{ github.event.inputs.branch }}