name: Cleanup cache by a branch
on:
  workflow_dispatch:
    inputs:
      branch:
        description: branch 
        required: false
        default: 'main'

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: "${{ github.ref }}"
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Clean cache
        uses: './.github/actions/clean-cache'
        with:
          secret_token: ${{ secrets.WF_NEW }}
          branch: ${{ github.event.inputs.branch }}
