name: Cleanup cache by a branch
on:
  workflow_dispatch:
    inputs:
      branch:
        description: branch 
        required: false
        default: 'main'

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Clean cache
        uses: './.github/actions/clean-cache'
        with:
          secret_token: ${{ secrets.WF_PAT }}
          branch: ${{ github.event.inputs.branch }}
