name: Triggering Workflow

on:
    workflow_dispatch:
      inputs:
        project:
          required: true
          type: choice
          description: 'Project name'
          options:
            - 'QANOV'
            - 'QABP'

jobs:
  get_basenames_and_trigger_workflows:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
  
      - name: Trigger workflows for QANOV app
        if: ${{ inputs.project == 'QANOV'}}
        env:
          FEATURES_PATH: "./acceptance/features/e2e/app/novum"
          EXCLUDED_PATH_REGEX: '.*\/(_setup|jenkins|steps|__pycache__)|novum$'
        uses: './.github/actions/trigger-jira-wf'
        with:
          secret_token: ${{ secrets.WF_PAT }}
          project: ${{ github.event.inputs.project }}
          features_path: ${{ env.FEATURES_PATH }}
          excluded_path: ${{ env.EXCLUDED_PATH_REGEX }}

      - name: Trigger workflows for QANOV web
        if: ${{ inputs.project == 'QANOV'}}
        id: set-matrix-base
        env:
          FEATURES_PATH: "./acceptance/features/e2e/web/novum"
          EXCLUDED_PATH_REGEX: '.*\/(_setup|jenkins|steps|__pycache__)|novum$'
        uses: './.github/actions/trigger-jira-wf'
        with:
          secret_token: ${{ secrets.WF_PAT }}
          project: ${{ github.event.inputs.project }}
          features_path: ${{ env.FEATURES_PATH }}
          excluded_path: ${{ env.EXCLUDED_PATH_REGEX }}

      - name: Trigger workflows for QANOV cms
        if: ${{ inputs.project == 'QANOV'}}
        env:
          FEATURES_PATH: "./acceptance/features/e2e/web/cms"
          EXCLUDED_PATH_REGEX: '.*\/(_setup|jenkins|steps|__pycache__)|cms$'
        uses: './.github/actions/trigger-jira-wf'
        with:
          secret_token: ${{ secrets.WF_PAT }}
          project: ${{ github.event.inputs.project }}
          features_path: ${{ env.FEATURES_PATH }}
          excluded_path: ${{ env.EXCLUDED_PATH_REGEX }}

      - name: Trigger workflows for QABP
        if: ${{ inputs.project == 'QABP'}}
        env:
          FEATURES_PATH: "./acceptance/features/e2e/app/b2p"
          EXCLUDED_PATH_REGEX: '.*\/(_setup|jenkins|steps|__pycache__)|b2p$'
        uses: './.github/actions/trigger-jira-wf'
        with:
          secret_token: ${{ secrets.WF_PAT }}
          project: ${{ github.event.inputs.project }}
          features_path: ${{ env.FEATURES_PATH }}
          excluded_path: ${{ env.EXCLUDED_PATH_REGEX }}